title : dqylyln树梅派的空间
tagline: 树莓派 Programming Software Architecture Java Golang Raspberry Pi Web
author :
  name : dqylyln
  email : dqylyln@gmail.com
  github : dqylyln
  twitter : dqylyln
  feedburner : dqylyln

navigation :
  - posts.md  
  - archive.html
  - tags.html
  - categories.html
  - pages.html  
  - about.md
  